# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:17.2.5
  amd64: ghcr.io/hassio-addons/base:17.2.5
  armhf: ghcr.io/hassio-addons/base:17.2.5
  armv7: ghcr.io/hassio-addons/base:17.2.5
  i386: ghcr.io/hassio-addons/base:17.2.5
labels:
  org.opencontainers.image.title: "Audio Distributor add-on"
  org.opencontainers.image.description: "Multi-protocol audio distribution server with Snapcast, Spotify Connect, and AirPlay support."
  org.opencontainers.image.source: "https://github.com/corneyl/hassio-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
